# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LigFinder' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LigFinder
pod 'Alamofire', '~> 5.2'
pod 'SwiftyJSON', '~> 4.0'

end

target 'LigFinder WatchKit App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LigFinder WatchKit App
pod 'Alamofire', '~> 5.2'
pod 'SwiftyJSON', '~> 4.0'
end

target 'LigFinder WatchKit Extension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LigFinder WatchKit Extension
pod 'Alamofire', '~> 5.2'
pod 'SwiftyJSON', '~> 4.0'
end
